import { useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowUpRight, Filter, Gauge, Search, ShieldCheck } from "lucide-react";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { PageFrame, Breadcrumbs, Project, Status } from "./SiteChrome";

const categories=["All projects","AI & Machine Learning","SaaS","FinTech","EdTech","HealthTech","Developer Tools","E-commerce","Cybersecurity"];
function ProjectCard({project,onSave}:{project:Project;onSave:(id:number)=>void}){return <article className="project-card" data-cursor="VIEW"><div className="project-head"><div className={`project-logo ${project.color}`}>{project.logo}</div><div className="project-head-right"><span className="demo-tag">{project.isDemo?"DEMO LISTING":"LIVE LISTING"}</span><button className="icon-button" aria-label="Save project" onClick={()=>onSave(project.id)}>+</button></div></div><div className="project-kicker">{project.category}<span>·</span>{project.startup}</div><h3>{project.name}</h3><p>{project.description}</p><div className="tech-list">{project.tech.slice(0,3).map(t=><span key={t}>{t}</span>)}</div><div className="project-metrics"><div><small>REVENUE</small><b>{project.revenue}</b></div><div><small>USERS</small><b>{project.users}</b></div><div><small>ASKING</small><b data-cursor="PRICE">{project.price}</b></div></div><div className="project-foot"><Status>{project.status}</Status><Link className="text-button" data-cursor="VIEW" href={`/project/${project.id}`}>View project <ArrowUpRight size={15}/></Link></div></article>}
export default function Explore(){const [query,setQuery]=useState("");const [category,setCategory]=useState("All projects");const {isAuthenticated}=useAuth();const utils=trpc.useUtils();const filters=useMemo(()=>({search:query||undefined,category:category==="All projects"?undefined:category}),[query,category]);const projectsQuery=trpc.projects.list.useQuery(filters);const save=trpc.projects.save.useMutation({onSuccess:()=>utils.projects.list.invalidate()});return <PageFrame><section className="page-hero"><div className="container"><Breadcrumbs items={["Explore Projects"]}/><div className="eyebrow cyan"><i/> MARKETPLACE</div><h1>Explore Projects</h1><p>Discover startups and products available for acquisition.</p><div className="route-search" data-cursor="SEARCH"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects, technologies, industries..."/></div></div></section><section className="section marketplace-section"><div className="container"><div className="marketplace-heading"><div className="section-title"><div className="eyebrow"><i/> DEMO MARKETPLACE</div><h2>Find the right kind of value.</h2><p>All fictional projects, metrics, and financial figures are labeled as demonstration data.</p></div><Link className="primary-button" href="/list-project">List your project <ArrowUpRight size={15}/></Link></div><div className="category-strip">{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="filter-row"><div className="results-count"><b>{projectsQuery.data?.length??0}</b> demo projects found <span>·</span> sorted by relevance</div><button className="filter-button"><Filter size={15}/> Filters <span>8</span></button></div><div className="project-grid">{projectsQuery.isLoading?<div className="empty-state"><Gauge size={28}/><h3>Loading listings...</h3><p>Fetching projects from the marketplace database.</p></div>:projectsQuery.error?<div className="empty-state"><Search size={28}/><h3>Could not load listings</h3><p>Refresh the page and try again.</p></div>:(projectsQuery.data??[]).map(project=><ProjectCard key={project.id} project={project as Project} onSave={id=>{if(!isAuthenticated){startLogin();return}save.mutate({projectId:id})}}/>)}</div></div></section></PageFrame>}
