import { useMemo, useState } from "react";
import {
  ArrowDown, ArrowRight, ArrowUpRight, BarChart3, Blocks, BookOpenCheck,
  BriefcaseBusiness, Check, ChevronDown, ChevronRight, CircleAlert,
  CircleCheck, CircleDollarSign, Clock3, FileCheck2, FileText, Gauge,
  HandCoins, Handshake, Layers3, LineChart, LockKeyhole, Menu, Network,
  Orbit, Route, Scale, ShieldCheck, Sparkles, Target, Users, X, Zap,
} from "lucide-react";

type FlowState = "released" | "satisfied" | "rescue";
type RiskLevel = "LOW" | "MEDIUM" | "HIGH";
const navItems = [["Problem", "problem"], ["Solution", "solution"], ["How it works", "how-it-works"], ["Business model", "business-model"], ["Market", "market"]];
const problems = [
  ["01", "INNOVATION", "Years of work become a strategic asset.", "Startups spend years building products, technology, and communities that become valuable far beyond the transaction itself.", Sparkles],
  ["02", "ACQUISITION", "Ownership changes. Incentives change.", "A larger company may acquire a startup for technology, talent, users, intellectual property, or strategic reasons.", Handshake],
  ["03", "DISCONTINUATION", "The product can fall outside the new roadmap.", "After integration or a shift in strategy, the standalone product may be merged, abandoned, or discontinued.", Layers3],
  ["04", "USER IMPACT", "Users inherit the uncertainty.", "Access can disappear, communities can fragment, and migration can become costly or impossible on short notice.", Users],
] as const;
const cases = [
  ["Meebo", "Google", "2012", "Standalone products were subsequently discontinued.", "CONFIRMED FACT", "cyan"],
  ["Aardvark", "Google", "2010", "The service was later shut down.", "CONFIRMED FACT", "violet"],
  ["Pocket", "Mozilla", "2017", "Mozilla later announced the Pocket service would be discontinued.", "DOCUMENTED OUTCOME", "amber"],
] as const;
const riskProfiles = {
  ExampleAI: { level: "HIGH" as RiskLevel, score: 78, summary: "Several continuity signals are unresolved before close.", metrics: [["Product dependency", "HIGH", "high"], ["User dependency", "HIGH", "high"], ["Strategic overlap", "MEDIUM", "medium"], ["Continuity commitment", "LOW", "low"], ["Transition plan", "NONE", "none"]] },
  AtlasNote: { level: "MEDIUM" as RiskLevel, score: 54, summary: "The product has a transition path, but key commitments are still open.", metrics: [["Product dependency", "MEDIUM", "medium"], ["User dependency", "HIGH", "high"], ["Strategic overlap", "LOW", "low"], ["Continuity commitment", "MEDIUM", "medium"], ["Transition plan", "DRAFT", "medium"]] },
  Northstar: { level: "LOW" as RiskLevel, score: 22, summary: "Core continuity conditions are defined and a transition plan is in place.", metrics: [["Product dependency", "LOW", "low"], ["User dependency", "MEDIUM", "medium"], ["Strategic overlap", "LOW", "low"], ["Continuity commitment", "HIGH", "high"], ["Transition plan", "READY", "high"]] },
};

function Logo() { return <a href="#top" className="logo" aria-label="AcquiShield home"><span className="logo-mark"><ShieldCheck size={18} strokeWidth={2.5} /></span><span>Acqui<span>Shield</span></span></a>; }
function SectionIntro({ eyebrow, title, copy, dark = false }: { eyebrow: string; title: string; copy?: string; dark?: boolean }) { return <div className={`section-intro ${dark ? "section-intro-dark" : ""}`}><div className="eyebrow"><span className="eyebrow-dot" />{eyebrow}</div><h2>{title}</h2>{copy && <p>{copy}</p>}</div>; }
function ArrowLink({ children, href = "#contact" }: { children: React.ReactNode; href?: string }) { return <a className="arrow-link" href={href}>{children}<ArrowUpRight size={16} /></a>; }
function FlowNode({ icon: Icon, label, sub, active, onClick }: { icon: typeof ShieldCheck; label: string; sub?: string; active?: boolean; onClick?: () => void }) { return <button className={`flow-node ${active ? "flow-node-active" : ""}`} onClick={onClick}><span className="flow-icon"><Icon size={18} /></span><span><strong>{label}</strong>{sub && <small>{sub}</small>}</span></button>; }

export default function Home() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [flow, setFlow] = useState<FlowState>("released");
  const [profile, setProfile] = useState<keyof typeof riskProfiles>("ExampleAI");
  const risk = useMemo(() => riskProfiles[profile], [profile]);
  const go = (id: string) => { setMobileOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); };
  return <div className="site-shell" id="top">
    <div className="top-strip"><span><span className="status-dot" />A proposed startup concept for Nationwide Hackathon 2026</span><span className="top-strip-right">Product continuity infrastructure <ArrowRight size={14} /></span></div>
    <header className="site-nav"><div className="container nav-inner"><Logo /><nav className={mobileOpen ? "nav-links nav-links-open" : "nav-links"}>{navItems.map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setMobileOpen(false)}>{label}</a>)}<a className="nav-cta" href="#contact" onClick={() => setMobileOpen(false)}>Talk to us <ArrowUpRight size={15} /></a></nav><button className="menu-toggle" aria-label="Toggle navigation" onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? <X /> : <Menu />}</button></div></header>

    <main>
      <section className="hero section-grid" aria-labelledby="hero-title"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" />STARTUP CONTINUITY INFRASTRUCTURE</div><h1 id="hero-title">When a startup gets acquired, its product <em>shouldn’t</em> automatically disappear.</h1><p className="hero-lede">AcquiShield creates a financial continuity mechanism designed to protect valuable startup products, users, and innovation when ownership changes.</p><div className="hero-actions"><a className="button button-primary" href="#solution">See how it works <ArrowRight size={17} /></a><a className="button button-ghost" href="#contact">Talk to the team <ArrowUpRight size={17} /></a></div><div className="hero-proof"><div className="proof-avatars"><span>F</span><span>A</span><span>U</span></div><span>For founders, acquirers &amp; users</span><span className="proof-line" /><span className="mono-text">CONTINUITY / 01</span></div></div><div className="hero-visual"><div className="hero-orbit orbit-a" /><div className="hero-orbit orbit-b" /><div className="hero-glow" /><div className="bond-badge"><span className="badge-icon"><Zap size={15} /></span>Introducing the <b>Continuity Bond™</b></div><div className="hero-flow"><div className="flow-step muted-step"><span className="flow-kicker">01 / BUILD</span><strong>STARTUP</strong><small>Something valuable takes shape</small></div><div className="flow-connector" /><div className="flow-step"><span className="flow-kicker">02 / OWNERSHIP CHANGE</span><strong>ACQUISITION</strong><small>Value changes hands</small></div><div className="flow-connector" /><div className="flow-step highlight-step"><span className="flow-kicker">03 / PROTECTION LAYER</span><strong>CONTINUITY BOND</strong><small>A measurable commitment</small></div><div className="flow-branches"><div><CircleCheck size={16} /><span><b>PRODUCT CONTINUES</b><small>Bond conditions satisfied</small></span></div><div><CircleAlert size={16} /><span><b>RESCUE POOL</b><small>If conditions fail</small></span></div></div></div><div className="hero-grid-label">ACQ / 2026 <span>↗</span></div></div></div><div className="hero-bottom"><div className="container hero-bottom-inner"><span>01</span><span className="hero-rule" /><span>Product continuity should be considered when a startup is acquired.</span><a href="#problem">Explore the case <ArrowDown size={15} /></a></div></div></section>

      <section className="section section-white" id="problem"><div className="container"><SectionIntro eyebrow="THE PROBLEM" title="The acquisition can change everything." copy="A product can create real value for years, then become vulnerable the moment its ownership changes. The risk is not always visible in the transaction itself." /><div className="card-grid problem-grid">{problems.map(([num, label, title, body, Icon]) => <article className="feature-card" key={num}><div className="card-top"><span className="card-number">{num}</span><Icon size={20} /></div><div className="card-label">{label}</div><h3>{title}</h3><p>{body}</p></article>)}</div><div className="gap-callout"><div className="gap-icon"><Scale size={24} /></div><div><span className="eyebrow">THE GAP</span><h3>“Acquisition agreements protect the transaction. But what protects the product?”</h3></div><ArrowRight size={21} /></div></div></section>

      <section className="section section-ink problem-flow"><div className="container"><div className="split-heading"><SectionIntro dark eyebrow="TODAY’S DEFAULT PATH" title="The value can disappear between the lines." copy="A product’s continuity is often an operational decision made after the acquisition closes—not a condition designed into the deal." /><div className="flow-timeline">{[["01", "Startup builds product"], ["02", "Product gains users"], ["03", "Startup gets acquired"], ["04", "Acquirer changes strategy"], ["05", "Product may be discontinued"], ["06", "Users lose access"]].map(([num, label], i) => <div className="timeline-item" key={num}><span>{num}</span><div><b>{label}</b>{i < 5 && <ChevronDown size={15} />}</div></div>)}</div></div><div className="warning-banner"><CircleAlert size={21} /><span>There is no universal financial continuity mechanism attached to every acquisition.</span><span className="banner-tag">UNSOLVED</span></div></div></section>

      <section className="section section-mist" id="cases"><div className="container"><SectionIntro eyebrow="DOCUMENTED OUTCOMES" title="This has happened before." copy="Real examples show the continuity question is not hypothetical. They do not, by themselves, establish why a product was discontinued." /><div className="case-grid">{cases.map(([name, acquirer, year, outcome, marker, color]) => <article className="case-card" key={name}><div className="case-card-head"><span className={`case-mark ${color}`}>{marker}</span><ArrowUpRight size={18} /></div><div className="case-name">{name}</div><div className="case-meta"><span>Acquired by <b>{acquirer}</b></span><span className="case-year">{year}</span></div><div className="case-line" /><p>{outcome}</p><div className="case-source"><FileText size={14} /><span>Publicly documented acquisition / service outcome</span></div></article>)}</div><div className="note-row"><BookOpenCheck size={18} /><span><b>Evidence standard:</b> We separate confirmed facts from reported information, analysis, and hypothesis.</span></div></div></section>

      <section className="section solution-section" id="solution"><div className="container"><div className="solution-heading"><SectionIntro dark eyebrow="THE SOLUTION" title="Introducing the Continuity Bond™" copy="A financial commitment designed around product continuity—not a promise buried in a press release." /><div className="solution-side-note"><span className="mono-text">A NEW DEAL LAYER</span><p>At acquisition, the buyer and seller agree on measurable continuity conditions and a predefined financial commitment.</p></div></div><div className="bond-layout"><div className="bond-flow-card"><div className="bond-card-top"><span className="eyebrow">INTERACTIVE MECHANISM</span><span className="live-chip"><span />LIVE DEMO</span></div><div className="bond-flow"><FlowNode icon={Handshake} label="Acquisition" sub="Ownership changes" /><div className="bond-arrow"><ArrowDown size={18} /></div><FlowNode icon={FileCheck2} label="Continuity Bond created" sub="Conditions written into the deal" /><div className="bond-arrow"><ArrowDown size={18} /></div><FlowNode icon={LockKeyhole} label="Funds held independently" sub="Escrow-like structure" /><div className="bond-arrow"><ArrowDown size={18} /></div><FlowNode icon={Target} label="Continuity conditions" sub="Measurable, contractual, time-bound" /></div></div><div className="bond-outcomes"><span className="eyebrow">SELECT AN OUTCOME</span><div className="outcome-tabs"><button className={flow === "released" ? "selected" : ""} onClick={() => setFlow("released")}><CircleCheck size={17} /><span><b>Product continues</b><small>Bond released</small></span></button><button className={flow === "satisfied" ? "selected" : ""} onClick={() => setFlow("satisfied")}><Route size={17} /><span><b>Transition plan provided</b><small>Conditions satisfied</small></span></button><button className={flow === "rescue" ? "selected" : ""} onClick={() => setFlow("rescue")}><CircleAlert size={17} /><span><b>Conditions fail</b><small>Funds flow to Rescue Pool</small></span></button></div><div className={`outcome-result result-${flow}`}>{flow === "released" && <><CircleCheck size={26} /><div><span>CONDITION SATISFIED</span><strong>Bond released</strong><p>Product remains operational for the agreed period.</p></div></>}{flow === "satisfied" && <><Route size={26} /><div><span>CONDITION SATISFIED</span><strong>Transition is approved</strong><p>Users receive a documented path to what comes next.</p></div></>}{flow === "rescue" && <><CircleAlert size={26} /><div><span>CONTRACTUAL TRIGGER</span><strong>Rescue Pool activated</strong><p>Funds can support recovery or an orderly transition, subject to the agreement.</p></div></>}</div><div className="legal-micro"><LockKeyhole size={14} /> Proposed structure; not an existing regulated financial product.</div></div></div></div></section>

      <section className="section section-white" id="how-it-works"><div className="container"><SectionIntro eyebrow="THE OPERATING MODEL" title="Four steps from intent to continuity." /><div className="steps-grid">{([["01", "AGREE", "Buyer and seller define the continuity period, bond amount, product requirements, trigger conditions, and transition requirements.", BriefcaseBusiness], ["02", "PROTECT", "Funds are held in an independent escrow-like structure with clear release conditions.", LockKeyhole], ["03", "CONTINUE", "The acquirer keeps the product operational or provides the agreed transition plan.", CircleCheck], ["04", "RESCUE", "If contractual conditions are triggered, funds can support product recovery or transition.", HandCoins]] as const).map(([num, title, body, Icon]) => <article className="step-card" key={num}><span className="step-num">{num}</span><Icon size={22} /><h3>{title}</h3><p>{body}</p><ArrowUpRight size={17} /></article>)}</div><div className="rescue-panel"><div><div className="eyebrow">THE RESCUE POOL</div><h2>If the product stops, its value doesn’t have to.</h2><p>Continuity capital could help preserve optionality when a product can no longer continue under its current owner.</p></div><div className="rescue-items">{[["RELAUNCH", "Fund a new team capable of continuing the product."], ["PRESERVE", "Support technology and documentation where legally possible."], ["MIGRATE", "Help users transition to alternative services."], ["TRANSITION", "Support an independent operator or community taking over." ]].map(([title, body]) => <div key={title}><Check size={15} /><span><b>{title}</b><small>{body}</small></span></div>)}</div></div><p className="disclaimer">Actual deployment would depend on contractual, legal, regulatory, intellectual-property, and financial requirements.</p></div></section>

      <section className="section section-mist" id="business-model"><div className="container"><SectionIntro eyebrow="BUSINESS MODEL" title="A new layer of M&amp;A infrastructure." copy="AcquiShield can create value by making continuity measurable, structured, and easier to evaluate." /><div className="revenue-grid"><article className="revenue-card featured"><span className="revenue-num">01</span><CircleDollarSign size={24} /><h3>Structuring fees</h3><p>Transaction or structuring fees for creating and administering Continuity Bond arrangements.</p><div className="revenue-foot">Founders · Acquirers · Investors · M&amp;A advisors</div></article><article className="revenue-card"><span className="revenue-num">02</span><ShieldCheck size={24} /><h3>Risk coverage</h3><p>Partner-based continuity protection through appropriately licensed insurance or risk providers.</p><div className="partner-pill">Future partner-based model <span>Subject to applicable regulation</span></div></article><article className="revenue-card"><span className="revenue-num">03</span><BarChart3 size={24} /><h3>Continuity Risk Score™</h3><p>An analytical indicator built from publicly observable inputs associated with product-continuity risk.</p><div className="risk-scale"><span className="low">LOW</span><span className="medium">MEDIUM</span><span className="high">HIGH</span></div></article></div><div className="input-row"><span>Potential inputs</span>{["Acquisition structure", "Product overlap", "User dependency", "Transition plan", "Historical outcomes"].map(x => <span className="input-chip" key={x}>{x}</span>)}</div></div></section>

      <section className="section section-white" id="market"><div className="container"><div className="market-head"><SectionIntro eyebrow="MARKET OPPORTUNITY" title="The market is real. The continuity layer is missing." copy="We are deliberately not inventing a market-size number. The first version of AcquiShield should be built on verified research, not inflated slides." /><span className="research-badge"><LineChart size={16} /> Research-led</span></div><div className="stats-grid">{[["STARTUP ACQUISITIONS", "Research data required", "Relevant acquisition volume / value"], ["TECHNOLOGY M&amp;A", "Research data required", "Scale of the technology acquisition market"], ["PRODUCTS AT RISK", "Research data required", "Evidence on post-acquisition discontinuation"]].map(([label, value, body]) => <article className="stat-card" key={label}><span>{label}</span><strong>{value}</strong><p>{body}</p><ArrowUpRight size={18} /></article>)}</div><div className="tam-map"><div className="tam-title"><span className="eyebrow">INITIAL MARKET WEDGE</span><h3>TAM <ArrowDown size={17} /> SAM <ArrowDown size={17} /> SOM</h3></div><div className="tam-layers"><div className="tam-layer tam"><span>TAM</span><b>Global startup &amp; technology M&amp;A</b></div><div className="tam-layer sam"><span>SAM</span><b>Technology acquisitions where product continuity matters</b></div><div className="tam-layer som"><span>SOM</span><b>Initial focus: Indian technology startups &amp; transactions</b></div></div></div></div></section>

      <section className="section section-ink why-section"><div className="container"><SectionIntro dark eyebrow="WHY ACQUISHIELD" title="We’re not blocking acquisitions. We’re protecting optionality." /><div className="why-grid">{([["FOR FOUNDERS", "Protect the long-term value and continuity of the product they built.", Target], ["FOR USERS", "Increase the possibility of an orderly transition if a product is discontinued.", Users], ["FOR ACQUIRERS", "Create a structured and transparent way to address product-continuity commitments.", Handshake]] as const).map(([label, body, Icon]) => <article key={label}><Icon size={22} /><span>{label}</span><p>{body}</p><ArrowUpRight size={17} /></article>)}</div></div></section>

      <section className="section section-mist dashboard-section"><div className="container dashboard-layout"><div><SectionIntro eyebrow="INTERACTIVE DEMO" title="Continuity Risk Analyzer" copy="Explore fictional examples of how continuity signals could be made visible before a deal closes." /><div className="profile-select">{(Object.keys(riskProfiles) as Array<keyof typeof riskProfiles>).map(name => <button className={profile === name ? "active" : ""} onClick={() => setProfile(name)} key={name}>{name}<ChevronRight size={15} /></button>)}</div><p className="demo-note"><CircleAlert size={15} /> Demo data only. This score does not represent any real company or acquisition.</p></div><div className="dashboard-card"><div className="dashboard-top"><div><span className="eyebrow">CONTINUITY RISK</span><h3>{profile}</h3></div><span className={`risk-bubble ${risk.level.toLowerCase()}`}>{risk.level}</span></div><div className="score-row"><div className="score-number">{risk.score}<small>/100</small></div><div className="score-track"><span style={{ width: `${risk.score}%` }} /></div></div><p className="score-summary">{risk.summary}</p><div className="metric-list">{risk.metrics.map(([label, value, tone]) => <div className="metric" key={label}><span>{label}</span><b className={`metric-${tone}`}>{value}</b></div>)}</div><div className="dashboard-foot"><Gauge size={16} /> Analytical indicator of product-continuity risk</div></div></div></section>

      <section className="section section-white trust-section"><div className="container"><SectionIntro eyebrow="TRUST &amp; TRANSPARENCY" title="Built on evidence, not accusations." /><div className="trust-grid">{([["VERIFIED", "Use official announcements and reliable sources.", BookOpenCheck], ["TRANSPARENT", "Separate confirmed information from reports and speculation.", Network], ["CONTRACTUAL", "Define continuity requirements before the acquisition closes.", FileCheck2]] as const).map(([label, body, Icon]) => <div className="trust-card" key={label}><Icon size={23} /><span>{label}</span><p>{body}</p></div>)}</div><blockquote>“AcquiShield does not assume why a product was discontinued. It focuses on creating a mechanism for what happens next.”</blockquote></div></section>

      <section className="section flywheel-section"><div className="container"><div className="flywheel-copy"><SectionIntro dark eyebrow="THE FLYWHEEL" title="Better data creates better deals." copy="Each continuity event creates learning that can improve the next structure, the next commitment, and the next preserved product." /><ArrowLink href="#contact">Build the continuity layer</ArrowLink></div><div className="flywheel"><div className="flywheel-ring" /><div className="flywheel-core"><Orbit size={23} /><span>MORE<br />OPTIONALITY</span></div>{[["Acquisitions", "top"], ["Continuity data", "right-top"], ["Risk analysis", "right-bottom"], ["Better structuring", "bottom"], ["More bonds", "left-bottom"], ["Larger Rescue Pool", "left-top"]].map(([label, pos]) => <div className={`wheel-node ${pos}`} key={label}><span>{label}</span></div>)}</div></div></section>

      <section className="final-cta" id="contact"><div className="container"><div className="final-cta-inner"><div className="eyebrow"><span className="eyebrow-dot" />THE NEXT DEAL LAYER</div><h2>Make product continuity<br /><em>part of the deal.</em></h2><p>Acquisitions can create value without making innovation disposable.</p><div className="hero-actions"><a className="button button-primary" href="mailto:hello@acquishield.example">Talk to the team <ArrowUpRight size={17} /></a><a className="button button-ghost light" href="mailto:hello@acquishield.example?subject=AcquiShield demo">Request a demo <ArrowRight size={17} /></a></div><div className="final-meta"><div><span>AcquiShield</span><small>Protecting product continuity in the startup economy.</small></div><div><span>Nationwide Hackathon 2026</span><small>Founders · Acquirers · Users</small></div></div></div></div></section>
    </main>

    <footer className="site-footer"><div className="container footer-grid"><div><Logo /><p>Protecting product continuity in the startup economy.</p></div><div className="footer-links">{navItems.map(([label, id]) => <a href={`#${id}`} key={id}>{label}</a>)}<a href="#contact">Contact</a></div><div className="footer-legal">AcquiShield is a proposed startup concept developed for a hackathon. The Continuity Bond, Rescue Pool, and related financial mechanisms would require legal, regulatory, financial, and contractual implementation.</div></div></footer>
  </div>;
}
