import { useState } from "react";
import { Link } from "wouter";
import { ArrowRight, Check, CircleAlert, FileCheck2, Handshake, LockKeyhole, Search, ShieldCheck, Sparkles, Users } from "lucide-react";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { PageFrame, Breadcrumbs } from "./SiteChrome";

const pageData={
 "how-it-works":{eyebrow:"THE PLATFORM FLOW",title:"From build to acquisition, without the dead ends.",copy:"A clear path for founders who built something valuable and companies looking for a faster route to ownership.",steps:["Build","List","Set price","Get discovered","Receive offers","Negotiate","Due diligence","Acquire"]},
 startups:{eyebrow:"FOR FOUNDERS",title:"Give what you built a clearer next chapter.",copy:"StartupXchange helps founders package context, reach potential buyers, receive offers, and move through a structured acquisition workflow.",steps:["List your product","Set your asking price","Reach potential buyers","Receive offers","Negotiate","Complete diligence","Close the acquisition"]},
 companies:{eyebrow:"FOR COMPANIES",title:"Discover focused acquisition opportunities.",copy:"Move from a broad market search to a short list of products, technology, and teams worth reviewing.",steps:["Discover projects","Filter opportunities","Review technology","Evaluate metrics","Contact founders","Make offers","Conduct diligence","Acquire"]},
 offers:{eyebrow:"OFFERS & NEGOTIATION",title:"Turn interest into a structured conversation.",copy:"Offers are persistent records that help buyers and sellers clarify amount, assets, conditions, and next steps.",steps:["Asking price","Buyer offer","Seller response","Counter offer","Negotiation","Agreement"]},
 "due-diligence":{eyebrow:"DUE DILIGENCE",title:"A clear review workflow for serious acquisitions.",copy:"Track business, technology, legal, financial, IP, and team requests before decisions are made.",steps:["Business","Technology","Legal","Financial","Intellectual property","Team"]}
} as const;
export function InfoPage({kind}:{kind:keyof typeof pageData}){const data=pageData[kind];return <PageFrame><section className="page-hero"><div className="container"><Breadcrumbs items={[data.eyebrow]}/><div className="eyebrow cyan"><i/> {data.eyebrow}</div><h1>{data.title}</h1><p>{data.copy}</p></div></section><section className="section"><div className="container"><div className="route-step-grid">{data.steps.map((step,i)=><article className="route-step-card" key={step}><span>0{i+1}</span><Sparkles size={19}/><h3>{step}</h3><p>{kind==="due-diligence"?"Status, documents, reviewer notes, and evidence can be tracked here.":"A focused step in a professional marketplace journey."}</p>{i<data.steps.length-1&&<ArrowRight size={15}/>}</article>)}</div>{kind==="due-diligence"&&<div className="disclaimer-card"><CircleAlert size={18}/><p>StartupXchange provides workflow and marketplace tools. Legal, financial, tax, and professional due diligence should be conducted with qualified professionals.</p></div>}{kind==="offers"&&<div className="route-two-column route-dark-card"><div><div className="eyebrow"><i/> LIVE WORKSPACE</div><h2>Manage offers from your dashboard.</h2><p>For logged-in users, offer records connect to their workspace for follow-up.</p></div><Link className="primary-button" href="/dashboard/company">Open dashboard <ArrowRight size={15}/></Link></div>}</div></section><section className="final-market-cta"><div className="container"><h2>{kind==="companies"?"Find your next advantage.":kind==="startups"?"List what you built.":"Keep the deal flow moving."}</h2><p>Use the dedicated pages to move through the marketplace at your own pace.</p><div className="hero-buttons"><Link className="primary-button" href={kind==="startups"?"/list-project":"/explore"}>{kind==="startups"?"List your project":"Explore projects"} <ArrowRight size={15}/></Link></div></div></section></PageFrame>}

export function ContinuityBond(){return <PageFrame><section className="page-hero"><div className="container"><Breadcrumbs items={["Continuity Bond"]}/><div className="eyebrow cyan"><i/> OPTIONAL CONTINUITY LAYER</div><h1>Protect what happens after acquisition.</h1><p>An acquisition can result in a product continuing, being integrated, transitioned, or discontinued. A proposed Continuity Bond can define agreed post-acquisition continuity or transition conditions.</p></div></section><section className="section"><div className="container"><div className="route-two-column"><div className="section-title"><div className="eyebrow"><i/> PROPOSED PLATFORM FEATURE</div><h2>Acquisition with the next chapter in view.</h2><p>This is not an existing legally enforceable financial product. It is a proposed workflow concept requiring appropriate legal and financial implementation.</p><div className="bond-note"><ShieldCheck size={20}/><span><b>Clearly labeled proposal</b><small>Parties should work with qualified professionals.</small></span></div></div><div className="route-step-stack">{["Acquisition","Continuity agreement","Defined conditions","Monitoring","Continue / transition"].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b>{i<4&&<ArrowRight size={15}/>}</div>)}</div></div></div></section></PageFrame>}

export function About(){return <PageFrame><section className="page-hero"><div className="container"><Breadcrumbs items={["About"]}/><div className="eyebrow cyan"><i/> ABOUT STARTUPXCHANGE</div><h1>A focused marketplace for what founders build next.</h1><p>StartupXchange is a prototype concept for organizing startup, product, technology, and team acquisitions with better context and clearer workflows.</p></div></section><section className="section"><div className="container route-preview-grid"><article className="route-preview-card"><ShieldCheck size={21}/><b>Trust by design</b><p>Verification, diligence, and audit-ready workflows belong in the product experience.</p></article><article className="route-preview-card"><Handshake size={21}/><b>Conversation first</b><p>Offers and negotiation should be structured without pretending a transaction happened automatically.</p></article><article className="route-preview-card"><Users size={21}/><b>Demo data clearly labeled</b><p>Fictional listings and financial figures are shown as demonstration data.</p></article></div></section></PageFrame>}
export function Contact(){return <PageFrame><section className="page-hero"><div className="container"><Breadcrumbs items={["Contact"]}/><div className="eyebrow cyan"><i/> CONTACT</div><h1>Talk through the next move.</h1><p>Use the form below for prototype feedback, marketplace questions, or partnership ideas.</p></div></section><section className="section"><div className="container auth-layout"><form className="auth-card"><label>Name<input placeholder="Your name"/></label><label>Email<input type="email" placeholder="you@company.com"/></label><label>Message<textarea placeholder="How can we help?"/></label><button className="primary-button" type="button">Send message <ArrowRight size={15}/></button></form><div className="route-dark-card"><MessageIcon/><h2>Professional by default.</h2><p>StartupXchange is a prototype marketplace. Actual legal, financial, and transaction matters should be handled by qualified professionals.</p></div></div></section></PageFrame>}
function MessageIcon(){return <ShieldCheck size={25}/>}
export function AuthPage({signup=false}:{signup?:boolean}){const [role,setRole]=useState<"startup"|"company">("startup");return <PageFrame><section className="page-hero auth-hero"><div className="container"><Breadcrumbs items={[signup?"Sign Up":"Login"]}/><div className="auth-layout"><div><div className="eyebrow cyan"><i/> SECURE ACCESS</div><h1>{signup?"Create your marketplace account.":"Welcome back to StartupXchange."}</h1><p>{signup?"Choose how you participate in the acquisition marketplace.":"Sign in to manage listings, saved projects, offers, and diligence workflows."}</p></div><div className="auth-card"><div className="role-toggle"><button className={role==="startup"?"active":""} onClick={()=>setRole("startup")}>I'm a startup</button><button className={role==="company"?"active":""} onClick={()=>setRole("company")}>I'm a company</button></div>{signup&&<label>{role==="startup"?"Founder name":"Representative name"}<input placeholder="Your name"/></label>}<label>{signup?role==="startup"?"Startup name":"Company name":"Email"}<input placeholder={signup?"Organization name":"you@company.com"}/></label>{signup&&<label>Company website<input placeholder="https://"/></label>}<label>Email<input type="email" placeholder="you@company.com"/></label><label>Password<input type="password" placeholder="••••••••"/></label><button className="primary-button" onClick={()=>startLogin()}>{signup?"Continue":"Log in"} <ArrowRight size={15}/></button><Link className="text-button" href={signup?"/login":"/signup"}>{signup?"Already have an account? Log in":"Create account"}</Link></div></div></div></section></PageFrame>}

export function RoleDashboard({role}:{role:"startup"|"company"}){const {user}=useAuth();const summary=trpc.dashboard.summary.useQuery(undefined,{enabled:Boolean(user)});const startup=role==="startup";return <PageFrame><section className="page-hero"><div className="container"><Breadcrumbs items={["Dashboard",startup?"Startup":"Company"]}/><div className="eyebrow cyan"><i/> {startup?"STARTUP DASHBOARD":"COMPANY DASHBOARD"}</div><h1>{startup?"Manage what you built.":"Manage what you want to acquire."}</h1><p>{user?"Your authenticated workspace is connected to live data.":"Sign in to load your persistent marketplace activity."}</p></div></section><section className="section"><div className="container"><div className="dashboard-route-grid">{(startup?["Listed projects","Project views","Interested companies","Offers received","Active negotiations","Completed acquisitions"]:["Saved projects","Active offers","Negotiations","Due diligence","Acquisitions"]).map((label,i)=><article className="workspace-metric" key={label}><span>{label.toUpperCase()}</span><b>{user&&i===0?summary.data?.listedProjects??0:"—"}</b><small>{user?"Live workspace data":"Sign in to load"}</small></article>)}</div><div className="route-dashboard-panel"><div className="eyebrow"><i/> WORKSPACE NAVIGATION</div><div className="route-chip-grid">{(startup?["Overview","My Projects","Offers","Negotiations","Due Diligence","Messages","Documents","Profile"]:["Overview","Explore","Saved Projects","Offers","Negotiations","Due Diligence","Messages","Profile"]).map(item=><Link href={item==="Explore"?"/explore":"/workspace"} key={item}>{item}<ArrowRight size={14}/></Link>)}</div></div></div></section></PageFrame>}
export function AdminDashboard(){return <PageFrame><section className="page-hero"><div className="container"><Breadcrumbs items={["Admin Dashboard"]}/><div className="eyebrow cyan"><i/> ADMIN CONTROL CENTER</div><h1>Review the marketplace responsibly.</h1><p>Admin workflows are separated from public discovery and designed around review, moderation, and platform health.</p></div></section><section className="section"><div className="container"><div className="dashboard-route-grid">{["User management","Project management","Verification","Reports","Listings","Transactions","Disputes","Continuity agreements","Platform analytics"].map(item=><article className="route-admin-card" key={item}><ShieldCheck size={18}/><b>{item}</b><small>Review queue · demo</small></article>)}</div><div className="disclaimer-card"><LockKeyhole size={18}/><p>Admin actions should be protected by role-based access control. This prototype displays the admin information architecture without claiming real moderation activity.</p></div></div></section></PageFrame>}
