import { useEffect, useState } from "react";
import { Link, useLocation } from "wouter";
import { ArrowRight, Home as HomeIcon, Menu, Network, Plus, Search, ShieldCheck, Sparkles, X } from "lucide-react";

export type Project = { id:number; name:string; startup:string; category:string; description:string; tech:string[]; status:string; revenue:string; users:string; price:string; acquisitionType:string; color:string; logo:string; isDemo:number; };

export function CustomCursor(){
 const [point,setPoint]=useState({x:-100,y:-100,visible:false,label:"",interactive:false}); const [trail,setTrail]=useState<{x:number;y:number}[]>([]);
 useEffect(()=>{document.body.classList.add("custom-cursor-active");const move=(event:MouseEvent)=>{const target=event.target as HTMLElement;const field=target.closest('input,textarea,select,[contenteditable="true"]');const hit=target.closest("[data-cursor]") as HTMLElement|null;const label=field?"":(hit?.dataset.cursor||"");setPoint({x:event.clientX,y:event.clientY,visible:!field,label,interactive:Boolean(hit&&!field)});if(!field)setTrail(prev=>[{x:event.clientX,y:event.clientY},...prev].slice(0,4));};const leave=()=>setPoint(prev=>({...prev,visible:false}));window.addEventListener("mousemove",move,{passive:true});window.addEventListener("mouseout",leave);return()=>{document.body.classList.remove("custom-cursor-active");window.removeEventListener("mousemove",move);window.removeEventListener("mouseout",leave)}},[]);
 return <div className={`custom-cursor-layer ${point.visible?"is-visible":""} ${point.interactive?"is-interactive":""} ${point.label?"has-label":""}`} style={{"--cursor-x":`${point.x}px`,"--cursor-y":`${point.y}px`} as React.CSSProperties} aria-hidden="true"><span className="cursor-trail trail-1" style={{left:trail[1]?.x??point.x,top:trail[1]?.y??point.y}}/><span className="cursor-trail trail-2" style={{left:trail[2]?.x??point.x,top:trail[2]?.y??point.y}}/><span className="cursor-trail trail-3" style={{left:trail[3]?.x??point.x,top:trail[3]?.y??point.y}}/><span className="cursor-ring">{point.label&&point.label!=="NAV"&&<b>{point.label}</b>}</span><span className="cursor-dot"/></div>;
}

export function OpeningSequence(){const [show,setShow]=useState(false);useEffect(()=>{try{if(!sessionStorage.getItem("sx-opening-seen")){setShow(true);const timer=window.setTimeout(()=>{sessionStorage.setItem("sx-opening-seen","1");setShow(false)},4100);return()=>window.clearTimeout(timer)}}catch{setShow(true)}},[]);if(!show)return null;return <div className="opening-sequence" aria-hidden="true"><div className="opening-stars"><i/><i/><i/><i/><i/></div><div className="opening-core"><div className="opening-mark"><Network size={27}/></div><div className="opening-name">Startup<span>Xchange</span></div><div className="opening-tagline">BUILD IT · LIST IT · GET ACQUIRED</div><div className="opening-progress"><i/></div><div className="opening-status">INITIALIZING MARKETPLACE <b>·</b> READY</div></div></div>}

function Logo(){return <Link className="brand" href="/"><span className="brand-mark"><Network size={18}/></span><span>Startup<span>Xchange</span></span></Link>}
const nav=[ ["/","Home",HomeIcon], ["/explore","Explore projects",Search], ["/how-it-works","How it works",Sparkles], ["/startups","For startups",Plus], ["/continuity-bond","Continuity bond",ShieldCheck] ] as const;
export function SiteChrome(){const [open,setOpen]=useState(false);const [location]=useLocation();return <><CustomCursor/><OpeningSequence/><div className="notice-bar"><span><i/> Professional startup acquisition marketplace · demo data is clearly labeled</span><span>Build it. List it. Get acquired. <ArrowRight size={13}/></span></div><header className={`main-nav ${open?"open":""}`}><div className="nav-rail"><div className="nav-rail-head"><Logo/></div><div className="nav-toggle-wrap"><button className="nav-toggle" aria-label={open?"Collapse navigation":"Expand navigation"} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X size={17}/>:<Menu size={17}/>}</button></div><nav className="nav-menu">{nav.map(([href,label,Icon])=><Link data-cursor="NAV" key={href} className={location===href?"active":undefined} href={href} onClick={()=>setOpen(false)}><Icon size={16}/><span>{label}</span></Link>)}<Link data-cursor="OPEN" className="nav-list" href="/list-project" onClick={()=>setOpen(false)}><Plus size={15}/><span>List your project</span></Link><Link className="nav-auth" href="/login" onClick={()=>setOpen(false)}><span>Log in</span></Link><Link className="nav-auth" href="/signup" onClick={()=>setOpen(false)}><span>Sign up</span></Link></nav></div></header></>}

export function PageFrame({children,active}:{children:React.ReactNode;active?:string}){return <div className="market-shell route-shell" id="top"><SiteChrome/><main className="route-main">{children}</main><footer className="footer route-footer"><div className="container footer-row"><div><Logo/><p>Build it. List it. Get acquired.</p></div><div className="footer-links"><Link href="/about">About</Link><Link href="/contact">Contact</Link><Link href="/due-diligence">Due diligence</Link><Link href="/offers">Offers</Link></div><span className="footer-legal">StartupXchange is a prototype marketplace. Demo listings and statistics are fictional.</span></div></footer></div>}
export function Breadcrumbs({items}:{items:string[]}){return <div className="breadcrumbs"><Link href="/"><HomeIcon size={12}/> Home</Link>{items.map((item,index)=><span key={`${item}-${index}`}><span>/</span>{item}</span>)}</div>}
export function Status({children}:{children:string}){return <span className={`status-pill ${children.includes("OPEN")?"open":children.includes("DUE")?"review":"negotiating"}`}><i/>{children}</span>}
